### ISSUE TITLE
No idea to improve the UX/IX.

### ISSUE THREAD

**Issue by glydzo** [tohsic-7/d7020e---assignment3#1]
You gave a score of 4. So do you have any idea of what could be a good improvement ?

https://github.com/tohsic-7/d7020e---assignment3/blob/dd817ff66771de0bb5ab16d7cec87cb63613d976/cargo_klee_examples/examples/get_sign.rs#L91-L93

**Comment by tohsic-7** [comment]
Yes I wrote in the task above that it would benefit from an easier installation IMO. I'll split the previous answer and paste that part into this question

**Comment by glydzo** [comment]
Oh yes, I hadn't noticed.
