### ISSUE TITLE
Klee-analysis : No answer 

### ISSUE THREAD

**Issue by ThomasBoquelet** [tohsic-7/d7020e---assignment3#3]
https://github.com/tohsic-7/d7020e---assignment3/blob/dd817ff66771de0bb5ab16d7cec87cb63613d976/cargo_klee_examples/examples/get_sign.rs#L105

You should check the following link.
https://gitlab.henriktjader.com/KLEE/klee-sys/-/blob/master/src/lib.rs#L19-25

**Comment by tohsic-7** [comment]
I didn't know the answer thanks for the link!
