### ISSUE TITLE
Wrong place for the answer

### ISSUE THREAD

**Issue by ThomasBoquelet** [tohsic-7/d7020e---assignment3#4]
https://github.com/tohsic-7/d7020e---assignment3/blob/dd817ff66771de0bb5ab16d7cec87cb63613d976/cargo_klee_examples/examples/get_sign.rs#L88-L93

You need to divide your answer in two. Then the part where you add a comment to improve should be below the question. But that's a small detail anyway.

**Comment by tohsic-7** [comment]
Ok thanks!
